// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odfptispulkgocnaufbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZnB0aXNwdWxrZ29jbmF1ZmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTgzNjksImV4cCI6MjA1OTA3NDM2OX0.ZN7D74NIk3Q75YwUnhgZBpubjdcsEg55HvanrI2E-6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);